package staticdata;


public enum Currency {
	USD, EUR, JPY, GBP, AUD, CHF, CAD, HKD, SEK, NZD, KRW, SGD, MXN, NOK, ZAR, DKK, ILS, CNY, RUB, TRY, BRI, INR, PLN, TWD, HUF, MYR, CZK, THB
    , CLP, IDR, AED, ARS, BHD, BRL, COP, EGP, GHS, HRK, ISK, KWD, KZT, LTL, MAD, NGN, OMR, PEN, PHP, QAR, RON, SAR, TND, XAG, XAU, XGE, XPD, XPT
    , XSE, CRC, DZD, KES, LBP, LKR, TZS, UAH, UYU, WST, KRX, TWX, BRX, CNX, MXV, MYX, RPI, SGX, RUX, SKK, THX, UNK, VND
}
